# Generated by Django 6.0 on 2025-12-22 10:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeMedical',
            fields=[
                ('id_acte', models.AutoField(primary_key=True, serialize=False)),
                ('nom_acte', models.CharField(max_length=100)),
                ('prix_acte', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id_allerg', models.AutoField(primary_key=True, serialize=False)),
                ('nom_allerg', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id_analyse', models.AutoField(primary_key=True, serialize=False)),
                ('nom_analyse', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id_dossier', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id_employe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_empl', models.CharField(max_length=100)),
                ('prenom_empl', models.CharField(max_length=100)),
                ('cin_empl', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.CharField(blank=True, choices=[('RECEPTIONNISTE', 'Réceptionniste'), ('SECRETAIRE', 'Secrétaire Médicale'), ('ADMIN', 'Administrateur'), ('INFIRMIER', 'Infirmier(ère)')], default='RECEPTIONNISTE', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id_maladie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_malad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id_med', models.AutoField(primary_key=True, serialize=False)),
                ('nom_med', models.CharField(max_length=100)),
                ('prenom_med', models.CharField(max_length=100)),
                ('specialite_med', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismeAssurance',
            fields=[
                ('id_organisme', models.AutoField(primary_key=True, serialize=False)),
                ('nom_org', models.CharField(max_length=100)),
                ('type_org', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id_radio', models.AutoField(primary_key=True, serialize=False)),
                ('nom_rad', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id_vacc', models.AutoField(primary_key=True, serialize=False)),
                ('nom_vacc', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_recommandee', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('MEDECIN', 'Médecin'), ('RECEPTIONNISTE', 'Réceptionniste'), ('ADMIN', 'Administrateur')], default='PATIENT', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('cin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id_cons', models.AutoField(primary_key=True, serialize=False)),
                ('date_cons', models.DateField()),
                ('diagnostic', models.TextField()),
                ('prix_cons', models.FloatField()),
                ('consultation_initiale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.consultation')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_applique', models.FloatField(blank=True, null=True)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actemedical')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='AllergieDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precautions_patient', models.TextField(blank=True, null=True)),
                ('allergie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allergie')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dossiermedical')),
            ],
        ),
        migrations.CreateModel(
            name='MaladieDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_maladie_patient', models.CharField(blank=True, max_length=100, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dossiermedical')),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maladie')),
            ],
        ),
        migrations.CreateModel(
            name='JourTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('libre', models.BooleanField(default=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id_ordonnance', models.AutoField(primary_key=True, serialize=False)),
                ('date_ord', models.DateField()),
                ('medicaments', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='OrdonnanceAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ord', models.DateField()),
                ('analyse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.analyse')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.AutoField(primary_key=True, serialize=False)),
                ('nom_patient', models.CharField(max_length=100)),
                ('prenom_patient', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
                ('cin', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=20)),
                ('situation_familiale', models.CharField(max_length=100)),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.AutoField(primary_key=True, serialize=False)),
                ('date_fact', models.DateField()),
                ('type_facture', models.CharField(max_length=100)),
                ('montant', models.FloatField()),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.consultation')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
        migrations.CreateModel(
            name='PatientOrganisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organismeassurance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='OrdonnanceRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ord', models.DateField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultation')),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.radio')),
            ],
        ),
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.creneau')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='rdv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rdv'),
        ),
        migrations.CreateModel(
            name='VaccinDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vacc_patient', models.DateField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dossiermedical')),
                ('vaccin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vaccin')),
            ],
        ),
    ]
