# Generated by Django 6.0 on 2025-12-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cin',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
