# Generated by Django 6.0 on 2026-01-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_patient_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='statut',
            field=models.CharField(choices=[('RESERVE', 'Réservé'), ('CONFIRME', 'Confirmé'), ('EN_CONSULTATION', 'En consultation'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='RESERVE', max_length=20),
        ),
    ]
