# Generated by Django 6.0 on 2026-01-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='numero_ordre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='tarif_consultation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
