# Generated by Django 6.0 on 2026-01-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_medecin_adresse_medecin_email_medecin_numero_ordre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(blank=True, choices=[('RECEPTIONNISTE', 'Réceptionniste'), ('SECRETAIRE', 'Secrétaire Médicale'), ('INFIRMIER', 'Infirmier(ère)')], default='RECEPTIONNISTE', max_length=50, null=True),
        ),
    ]
