# Generated by Django 6.0 on 2026-01-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_medecin_numero_ordre'),
    ]

    operations = [
    ]
